#!/usr/bin/env python3

import subprocess
from functools import reduce

def read(file_path):
    file    = open(file_path, "r")
    content = file.read()
    file.close()
    return content

def syscall(args):
    return subprocess.run(args, stdout=subprocess.PIPE) \
              .stdout                                   \
              .decode('utf-8')                          \
              .split('\n')

files = syscall(["git", "diff", "feature/huubhr-re-arch", "--name-only"])
diffs = syscall(["git", "diff", "feature/huubhr-re-arch"])

file_contents = [[x, read(x).split('\n')] for x in files if x != '']
diff_contents = ([x for x in diffs if x != '' and x.startswith('+') and not x.startswith('++')])

for path, content in file_contents:
    i = 1 
    for line in content:
        if("print" in line):
            print('{}:{} println detected: {}'.format(path, i, line))
        i = i + 1
